#Wordpress container
version: "3.8"
services:
  wordpress:
    image: wordpress:latest
    container_name: wp-${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      TZ: ${TZ}
    volumes:
      - "html:/var/www/html"
      - "./php_config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro"
    labels:
      - "traefik.enable=true"
      # http  
      - "traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.services.${SERVICE}.loadbalancer.server.port=${SERVICE_PORT}"
      - "traefik.http.routers.${SERVICE}_redirect.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.${SERVICE}_redirect.entrypoints=web"
      # redirect to https
      - "traefik.http.routers.${SERVICE}.tls.certresolver=le"
      - "traefik.http.routers.${SERVICE}.entrypoints=web-secure"
      - "traefik.http.middlewares.${SERVICE}_https.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE}_redirect.middlewares=${SERVICE}_https"
      # auth with authelia
      #- "traefik.http.routers.${SERVICE}.middlewares=authelia@file"
      # auto update
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - db
    networks:
      - web
      - default
  db:
    image: mariadb:latest
#    command: mysqld --innodb-buffer-pool-size=64M
    container_name: db-${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    volumes:
      - "./mysql/datadir:/var/lib/mysql"
      - "./mysql/backup_mysql:/backup:ro"

    networks:
      - default
            
  adminer:
    container_name: adminer_${SERVICE}
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DESIGN: "nette"
      ADMINER_PLUGINS: "tables-filter tinymce"
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      # http  
      - "traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.services.${SERVICE}.loadbalancer.server.port=${SERVICE_PORT}"
      - "traefik.http.routers.${SERVICE}_redirect.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.${SERVICE}_redirect.entrypoints=web"
      # redirect to https
      - "traefik.http.routers.${SERVICE}.tls.certresolver=le"
      - "traefik.http.routers.${SERVICE}.entrypoints=web-secure"
      - "traefik.http.middlewares.${SERVICE}_https.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE}_redirect.middlewares=${SERVICE}_https"
      # auth with authelia
      # - "traefik.http.routers.${SERVICE}.middlewares=authelia@file"
      # auto update
      - "com.centurylinklabs.watchtower.enable=true"   

    networks:
      - web
      - default

  ftp:
    container_name: ftp_${SERVICE}
    image: stilliard/pure-ftpd:hardened
    ports:
      - "${FTP_PORT}:21"
      - "${FTP_PASV_START}-${FTP_PASV_END}:${FTP_PASV_START}-${FTP_PASV_END}"
    volumes:
      - "html:/home/ftpusers/html"
      - "./ftpd/passwd:/etc/pure-ftpd/passwd"
#      - "./ftpd/ssl:/etc/ssl/private/"
    environment:
      PUBLICHOST: "SERVER.IP.ADRESS"
#      ADDED_FLAGS: "-g root -z"
      FTP_USER_UID: 33
      FTP_USER_GID: 33
      FTP_USER_NAME: ${FTP_USERNAME}
      FTP_USER_PASS: ${FTP_PASSWORD}
      FTP_USER_HOME: "/home/ftpusers/"
    restart: unless-stopped
volumes:
  html:
    driver_opts:
      type: none
      device: ${PWD}/html
      o: bind

networks:
    web:
        external: true
