#Wordpress container
version: '3'
services:
#Database service
  db:
    image: mariadb:latest
    container_name: db-${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - "./mysql/datadir:/var/lib/mysql"
      - "./mysql/backup_mysql:/backup:ro"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    networks:
      - default
#docker exec some-mariadb sh -c 'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > /some/path/on/your/host/all-databases.sql
#Wordpress service
  wordpress:
    image: wordpress:latest
    container_name: wp-${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
#     VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    volumes:
      - "./html:/var/www/html"
    depends_on:
      - db

    networks:
      - webproxy
      - default

  ftp-server:
    container_name: ftp-${CONTAINER_NAME}
    image: stilliard/pure-ftpd:hardened
    ports:
      - "${FTP_PORT}:21"
      - "${FTP_RANGE}:30000-30009"
    volumes:
      - "./html:/home/ftpusers/www-data"
      - "./ftpd/passwd:/etc/pure-ftpd/passwd"
#      - "./ftpd/ssl:/etc/ssl/private/"
    environment:
      PUBLICHOST: ${VIRTUAL_HOST}
      ADDED_FLAGS: "-g root"
    restart: unless-stopped
# USER create in FTP Server:
# pure-pw useradd my_user -f /etc/pure-ftpd/passwd/pureftpd.passwd -m -u 31 -g 31 -d /home/ftpusers/www-data
# Change password:
# pure-pw passwd my_user -f /etc/pure-ftpd/passwd/pureftpd.passwd -m 

  adminer:
    container_name: adminer-${CONTAINER_NAME}
    image: adminer
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DESIGN: "nette"
      ADMINER_PLUGINS: "tables-filter tinymce"

networks:
  webproxy:
    external:
      name: webproxy
