#Wordpress container
version: '3'
services:
#Database service
  db:
    image: mariadb:latest
#    command: mysqld --innodb-buffer-pool-size=64M    
    container_name: db-${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - "./mysql/datadir:/var/lib/mysql"
      - "./mysql/backup_mysql:/backup:ro"
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro

    networks:
      - default
#docker exec some-mariadb sh -c 'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > /some/path/on/your/host/all-databases.sql
#Wordpress service
  wordpress:
    image: wordpress:latest
    container_name: wp-${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
#     VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${HOSTNAME}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    volumes:
      - "./html:/var/www/html"
      - "./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro"
    depends_on:
      - db

    networks:
      - webproxy
      - default

  adminer:
    container_name: adminer-${CONTAINER_NAME}
    image: adminer
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DESIGN: "nette"
      ADMINER_PLUGINS: "tables-filter tinymce"

networks:
  webproxy:
    external:
      name: webproxy
